[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2108976d8aa366a96fdf4ba0ea08e00f2dd25e4c"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "c05307ae4d8e1ee77bd5ee4abc8e4dff29da78c022648d3898cf93f2acf0c78f"
    url = "https://github.com/maleadt/GDB_jll.jl/releases/download/GDB-v10.1.0+2/GDB.v10.1.0.x86_64-linux-gnu-cxx11.tar.gz"
