[[GDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b74830a10f0737bb8259c2492376a02cc7e066fe"
libc = "glibc"
os = "linux"

    [[GDB.download]]
    sha256 = "180e8cc7fd4bd4e9374a3edb08bc58e2cfbb58be0807decd41de4aa563e33eb6"
    url = "https://github.com/maleadt/GDB_jll.jl/releases/download/GDB-v10.1.0+2/GDB.v10.1.0.x86_64-linux-gnu-cxx11.tar.gz"
